### ISSUE TITLE
No support Grails 3.3

### ISSUE THREAD

**Issue by aluismarte** [budjb/grails-jaxrs#34] opened 2017-05-13 16:25 UTC
Use a deprecated package of spring

New class on 
**org.springframework.boot.web.servlet.ServletListenerRegistrationBean**
Use
**import org.springframework.boot.context.embedded.ServletListenerRegistrationBean**

2017-05-13 12:20:17.196 ERROR --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/ServletListenerRegistrationBean
	at org.grails.plugins.jaxrs.JaxrsCoreGrailsPlugin$_doWithSpring_closure1.doCall(JaxrsCoreGrailsPlugin.groovy:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1426)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1027)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:408)
	at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:759)
	at grails.spring.BeanBuilder.beans(BeanBuilder.java:588)
	at grails.spring.BeanBuilder.invokeMethod(BeanBuilder.java:531)
	at org.grails.plugins.DefaultGrailsPlugin.doWithRuntimeConfiguration(DefaultGrailsPlugin.java:559)
	at org.grails.plugins.AbstractGrailsPluginManager.doRuntimeConfiguration(AbstractGrailsPluginManager.java:167)
	at grails.boot.config.GrailsApplicationPostProcessor.postProcessBeanDefinitionRegistry(GrailsApplicationPostProcessor.groovy:171)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:686)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:524)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:83)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:388)

**Comment by avscj** [comment] 2017-10-30 11:11
I am having a look at this, please check my [fork](https://github.com/avscj/grails-jaxrs). I almost got it to work, just seem to have broken the swagger integration. Hope I can do a pull request soon

**Comment by aluismarte** [comment] 2017-10-30 15:49
Now is work. I am waiting version 3.0.5 Thanks

**Comment by avscj** [comment] 2017-10-30 15:50
sorry, do you mean it works now using my forked version?

**Comment by budjb** [comment] 2017-10-30 15:56
Any plans on submitting a fix for this?

**Comment by avscj** [comment] 2017-10-30 15:58
Hi,

Yes, as soon as I confirm that the swagger integration is still working or fix it if it isn't

**Comment by budjb** [comment] 2017-10-30 15:59
Awesome thanks

**Comment by avscj** [comment] 2017-11-03 16:48
I have created a [pull request](https://github.com/budjb/grails-jaxrs/pull/36) for this although I can see the CI fails. I can reproduce it, although not obvious what is wrong in the configuration. Am trying to fix

**Comment by aluismarte** [comment] 2018-03-03 15:26
I still waiting a update for this plugins and use a grails update? when is update?

**Comment by avscj** [comment] 2018-03-06 01:20
Hi,

As the CI build has been fixed since my last message, all I am waiting for is for the owner to be happy with my pull request.

**Comment by budjb** [comment] 2018-10-01 20:17
This has been released. Thanks!

**Closed as completed by budjb** 2018-10-01 20:17 UTC
